// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm8RjERNRGiNACshr3lUpXjICr0zhH3Lc',
    appId: '1:763136355595:web:6b4778b0222fcb2033c60e',
    messagingSenderId: '763136355595',
    projectId: 'bloodapp-37285',
    authDomain: 'bloodapp-37285.firebaseapp.com',
    storageBucket: 'bloodapp-37285.appspot.com',
    measurementId: 'G-YPTSD2L8TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFFoEO1eSMfhONwM2kbOsn6xCvpi_meHg',
    appId: '1:763136355595:android:2c20e55a6d7d1e7d33c60e',
    messagingSenderId: '763136355595',
    projectId: 'bloodapp-37285',
    storageBucket: 'bloodapp-37285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBToNrAcBd7_QFfos6c-h2J8f3ZbrOEXAQ',
    appId: '1:763136355595:ios:4e187dcefa239d7433c60e',
    messagingSenderId: '763136355595',
    projectId: 'bloodapp-37285',
    storageBucket: 'bloodapp-37285.appspot.com',
    iosBundleId: 'com.example.bloodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBToNrAcBd7_QFfos6c-h2J8f3ZbrOEXAQ',
    appId: '1:763136355595:ios:8e77157e2eaaaffa33c60e',
    messagingSenderId: '763136355595',
    projectId: 'bloodapp-37285',
    storageBucket: 'bloodapp-37285.appspot.com',
    iosBundleId: 'com.example.bloodapp.RunnerTests',
  );
}
